spring:
  jpa:
    show-sql: true
output:
  ansi:
  enabled: always
logging:
  pattern:
    dateformat: "yyyy-MM-dd HH:mm:ss"

app:
  welcome-message: "Welcome to Spring blog!"
  admin-email: "admin@admin.com"
